export const splitForwarderAbi = [
  {
    type: 'constructor',
    inputs: [{ name: '_operator', type: 'address', internalType: 'address' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'register',
    inputs: [{ name: 'salt', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'setRule',
    inputs: [
      { name: 'userTag', type: 'bytes6', internalType: 'bytes6' },
      {
        name: 'recipients',
        type: 'tuple[]',
        internalType: 'struct SplitForwarder.Recipient[]',
        components: [
          { name: 'addr', type: 'address', internalType: 'address' },
          { name: 'percentBps', type: 'uint16', internalType: 'uint16' },
        ],
      },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'deactivate',
    inputs: [{ name: 'userTag', type: 'bytes6', internalType: 'bytes6' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'processDeposit',
    inputs: [
      { name: 'userTag', type: 'bytes6', internalType: 'bytes6' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'depositId', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'processBatch',
    inputs: [
      { name: 'userTags', type: 'bytes6[]', internalType: 'bytes6[]' },
      { name: 'tokens', type: 'address[]', internalType: 'address[]' },
      { name: 'amounts', type: 'uint256[]', internalType: 'uint256[]' },
      { name: 'depositIds', type: 'bytes32[]', internalType: 'bytes32[]' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'claim',
    inputs: [
      { name: 'userTag', type: 'bytes6', internalType: 'bytes6' },
      { name: 'token', type: 'address', internalType: 'address' },
      { name: 'amount', type: 'uint256', internalType: 'uint256' },
      { name: 'depositId', type: 'bytes32', internalType: 'bytes32' },
    ],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'function',
    name: 'getRule',
    inputs: [{ name: 'userTag', type: 'bytes6', internalType: 'bytes6' }],
    outputs: [
      {
        name: 'recipients',
        type: 'tuple[]',
        internalType: 'struct SplitForwarder.Recipient[]',
        components: [
          { name: 'addr', type: 'address', internalType: 'address' },
          { name: 'percentBps', type: 'uint16', internalType: 'uint16' },
        ],
      },
      { name: 'createdAt', type: 'uint64', internalType: 'uint64' },
      { name: 'active', type: 'bool', internalType: 'bool' },
    ],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'masterId',
    inputs: [],
    outputs: [{ name: '', type: 'bytes4', internalType: 'bytes4' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'operator',
    inputs: [],
    outputs: [{ name: '', type: 'address', internalType: 'address' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'processed',
    inputs: [{ name: '', type: 'bytes32', internalType: 'bytes32' }],
    outputs: [{ name: '', type: 'bool', internalType: 'bool' }],
    stateMutability: 'view',
  },
  {
    type: 'function',
    name: 'transferOperator',
    inputs: [{ name: 'newOperator', type: 'address', internalType: 'address' }],
    outputs: [],
    stateMutability: 'nonpayable',
  },
  {
    type: 'event',
    name: 'Split',
    inputs: [
      { name: 'userTag', type: 'bytes6', indexed: true, internalType: 'bytes6' },
      { name: 'token', type: 'address', indexed: true, internalType: 'address' },
      { name: 'amount', type: 'uint256', indexed: false, internalType: 'uint256' },
      { name: 'recipientCount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RuleSet',
    inputs: [
      { name: 'userTag', type: 'bytes6', indexed: true, internalType: 'bytes6' },
      { name: 'recipientCount', type: 'uint256', indexed: false, internalType: 'uint256' },
    ],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'RuleDeactivated',
    inputs: [{ name: 'userTag', type: 'bytes6', indexed: true, internalType: 'bytes6' }],
    anonymous: false,
  },
  {
    type: 'event',
    name: 'Registered',
    inputs: [{ name: 'masterId', type: 'bytes4', indexed: false, internalType: 'bytes4' }],
    anonymous: false,
  },
  { type: 'error', name: 'AlreadyClaimed', inputs: [] },
  { type: 'error', name: 'AlreadyProcessed', inputs: [] },
  { type: 'error', name: 'InvalidPercents', inputs: [] },
  { type: 'error', name: 'NoRule', inputs: [] },
  { type: 'error', name: 'NotOperator', inputs: [] },
  { type: 'error', name: 'NotRecipient', inputs: [] },
  { type: 'error', name: 'TransferFailed', inputs: [] },
] as const
